name: jackssallymc
favicon: null
layout_spectrum: 0.5770270621869713
typography_spectrum: 0.9673311242368072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.13545657019130886
  lightness: 0.470570097444579
  saturation: 0.3385764556005597
  rhythmicContrast: 0.40253908396698534
purpose: []
